### ISSUE TITLE
Split-apply-combine todo

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1616]
An issue to keep track of the things that are pending todo in split-apply-combine ecosystem:

- [ ] decide on behavior of map (but let us discuss it in a separate thread)
- [x] adding handling dropmissing kwarg
- [x] handling of #1460 (we still do not handle it)
- [ ] handling of mixing scalars and vectors
- [ ] writing test-cases for hard scenarios - especially for mixing different things in return values and duplicate column names
- [ ] extending `by` interface #1615
- [ ] check performance of categorical vs string for grouping https://discourse.julialang.org/t/dataframes-v0-15-0-released/18258/10
- [ ] consider adding a special code path for the case when a data frame is already sorted (**added**)

@nalimilan - please add if I missed anything

**Comment by bkamins** [comment]
The last point (categorical vs string as a grouping variable) also influences how we should set up tests in https://github.com/h2oai/db-benchmark/pull/51.
