### ISSUE TITLE
DataFrames.jl roadmap

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1678]
TO-DO for DataFrames.jl 1.0:

- [ ] crucial split-apply-combine decisions, https://github.com/JuliaData/DataFrames.jl/issues/1615, https://github.com/JuliaData/DataFrames.jl/issues/1554, https://github.com/JuliaData/DataFrames.jl/issues/1460
- [x] row-oriented API, https://github.com/JuliaData/DataFrames.jl/issues/1514, https://github.com/JuliaData/DataFrames.jl/issues/956
- [x] `setindex!` finish deprecation
- [x] consistent broadcasting, https://github.com/JuliaData/DataFrames.jl/pull/1643
- [x] `eachcol` cleanup, https://github.com/JuliaData/DataFrames.jl/pull/1613, https://github.com/JuliaData/DataFrames.jl/pull/1752
- [x] consistency of construction from `DataFrameRow` and `NamedTuple`, https://github.com/JuliaData/DataFrames.jl/pull/1580, https://github.com/JuliaData/DataFrames.jl/issues/1675, https://github.com/JuliaData/DataFrames.jl/issues/1670, https://github.com/JuliaData/DataFrames.jl/issues/1599, https://github.com/JuliaData/DataFrames.jl/issues/1573, https://github.com/JuliaData/DataFrames.jl/issues/1569, https://github.com/JuliaData/DataFrames.jl/issues/1191
- [x] decide on API provided, https://github.com/JuliaData/DataFrames.jl/pull/1224, https://github.com/JuliaData/DataFrames.jl/pull/916, https://github.com/JuliaData/DataFrames.jl/issues/1655, https://github.com/JuliaData/DataFrames.jl/issues/1596, https://github.com/JuliaData/DataFrames.jl/issues/1595, https://github.com/JuliaData/DataFrames.jl/issues/406
- [x] cartesian index for DataFrame, https://github.com/JuliaData/DataFrames.jl/issues/1610

TO-DO past DataFrames.jl 1.0 (but may go in before if ready)

- [ ] a better `describe`, https://github.com/JuliaData/DataFrames.jl/pull/1664, https://github.com/JuliaData/DataFrames.jl/pull/1539, https://github.com/JuliaData/DataFrames.jl/issues/1443, https://github.com/JuliaData/DataFrames.jl/issues/1436
- [ ] `vcat` review, https://github.com/JuliaData/DataFrames.jl/pull/1659
- [ ] better benchmarks, https://github.com/JuliaData/DataFrames.jl/pull/1626
- [ ] improvements in split-apply-combine, https://github.com/JuliaData/DataFrames.jl/pull/1620, https://github.com/JuliaData/DataFrames.jl/pull/1555, https://github.com/JuliaData/DataFrames.jl/issues/1616
- [ ] metadata, https://github.com/JuliaData/DataFrames.jl/pull/1458, https://github.com/JuliaData/DataFrames.jl/issues/35
- [ ] `pivot` function, https://github.com/JuliaData/DataFrames.jl/pull/1181
- [ ] `sample` function decision, https://github.com/JuliaData/DataFrames.jl/pull/997
- [ ] documentation improvements, https://github.com/JuliaData/DataFrames.jl/issues/1662
- [ ] change default `show` parameters, https://github.com/JuliaData/DataFrames.jl/issues/1631, https://github.com/JuliaData/DataFrames.jl/issues/1381, https://github.com/JuliaData/DataFrames.jl/issues/1272, https://github.com/JuliaData/DataFrames.jl/issues/1167, https://github.com/JuliaData/DataFrames.jl/issues/864, https://github.com/JuliaData/DataFrames.jl/issues/592
- [ ] get rid of deprecated code, https://github.com/JuliaData/DataFrames.jl/issues/1602
- [ ] `delete!` improvements, https://github.com/JuliaData/DataFrames.jl/issues/1378
- [ ] `replace` improvements, https://github.com/JuliaData/DataFrames.jl/issues/1377
- [ ] add indexing, https://github.com/JuliaData/DataFrames.jl/issues/1346
- [ ] type-stable DataFrame, https://github.com/JuliaData/DataFrames.jl/issues/1335, https://github.com/JuliaData/DataFrames.jl/issues/744
- [ ] handling duplicate column names in `join`, https://github.com/JuliaData/DataFrames.jl/issues/1333
- [ ] better categorical with `Char`, https://github.com/JuliaData/DataFrames.jl/issues/1282
- [ ] JSON interop, https://github.com/JuliaData/DataFrames.jl/issues/873
- [ ] lead/lag, https://github.com/JuliaData/DataFrames.jl/issues/791
- [ ] better `vcat`: https://github.com/JuliaData/DataFrames.jl/issues/659
- [ ] better reshaping, https://github.com/JuliaData/DataFrames.jl/issues/645
- [ ] `cor` for DataFrame, https://github.com/JuliaData/DataFrames.jl/issues/583
- [ ] col names slicing, https://github.com/JuliaData/DataFrames.jl/issues/393
- [ ] add lookup, https://github.com/JuliaData/DataFrames.jl/issues/120

CC @nalimilan @oxinabox

**Comment by oxinabox** [comment]
Update checklistg re: 
 - eachcol cleanup, #1613

**Comment by bkamins** [comment]
@nalimilan - apart from some recent PRs/Issues pending, there are two big outstanding things:
* crucial split-apply-combine decisions
* row-oriented API
before we can go 1.0 I think.

Both topics are your pet things, if I may say 😄. Do you have any opinion how we should move forward with it?

**Comment by bkamins** [comment]
OK - I am closing this as all things mentioned here are done (except for one small issue that is tracked).

Now we will track 1.0 milestone with milestone labels. You can find the list here https://github.com/JuliaData/DataFrames.jl/milestone/5.

In general we are really close to 0.20 release (probably a few days), and then final design decisions will be made before we fix the functionality for 1.0 release (the decisions are mainly in three areas: split-apply-combine, row-vs-column oriented API, and column transformation API, i.e. `:oldcol => f => :newcol` pattern).
