### ISSUE TITLE
Improve text/plain show for AbstractDataFrame

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2146]
These are things to consider when improving `show` for `AbstractDataFrame`:

- [x] correct handling of wide columns (https://github.com/JuliaData/DataFrames.jl/pull/2087)
- [ ] optionally change textual representation of `missing` (https://github.com/JuliaData/DataFrames.jl/pull/1688)
- [x] optionally remove type from heading (https://github.com/JuliaData/DataFrames.jl/issues/2116)
- [ ] avoid printing vertical bars to have more compact printout
- [ ] right align numbers and make decimal dot `.` in one row (like arrays do)
- [ ] correct the display problem when printout width is exactly the same as terminal width (we should use "terminal width-1" to determine skipping printing columns)
- [ ] correctly handle values spanning multiple lines
- [x] improve handling of very wide columns (maybe we should have some maximum width after which we clip the output like we now do for types), https://github.com/JuliaData/DataFrames.jl/issues/1272
- [ ] discuss whether names of all omitted columns should be printed at the end (like dplyr)
- [x] fix circular reference bug (https://github.com/JuliaData/DataFrames.jl/issues/2135)

**Comment by bkamins** [comment]
@nalimilan - please add to the list if you have something more

**Comment by bkamins** [comment]
PrettyTables.jl now handles these.
