### ISSUE TITLE
Release 1.0 tracking

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2640]
In this issue I will track and update things to finish for 1.0 release of DataFrames.jl.

Top priority:

- [ ] `combine` without transformations https://github.com/JuliaData/DataFrames.jl/pull/2633
- [x] finalize joins we need (`semijoin` and `antijoin` still) https://github.com/JuliaData/DataFrames.jl/issues/2340
- [ ] improve documentation https://github.com/JuliaData/DataFrames.jl/pull/2602 and https://github.com/JuliaData/DataFrames.jl/issues/2595
- [ ] make code more compiler friendly https://github.com/JuliaData/DataFrames.jl/pull/2597 and https://github.com/JuliaData/DataFrames.jl/issues/2566, and https://github.com/JuliaData/DataFrames.jl/issues/2516
- [ ] rethink design of `stack` and `unstack` https://github.com/JuliaData/DataFrames.jl/issues/2422, https://github.com/JuliaData/DataFrames.jl/issues/2414
- [ ] rethink workflows with filtered data frames https://github.com/JuliaData/DataFrames.jl/issues/2354 and https://github.com/JuliaData/DataFrames.jl/issues/2314
- [ ] update precompilation statements (@nalimilan hopefully can help with this), https://github.com/JuliaData/DataFrames.jl/issues/2642
- [x] update to Julia 1.7 changes https://github.com/JuliaData/DataFrames.jl/issues/2643
- [x] tests cleanup https://github.com/JuliaData/DataFrames.jl/pull/2644
- [ ] decide if we should use `UInt32` instead of `Int` in `GroupedDataFrame` and joins when we are sure that there are less groups than `UInt32` values. Also consider checking if grouped data frame is sorted before grouping

Nice to have:

- [ ] using multi-threading in other operations than split-apply combine https://github.com/JuliaData/DataFrames.jl/issues/2626
- [ ] handling of `GroupKey` comparisons https://github.com/JuliaData/DataFrames.jl/issues/2639
- [ ] API of `eachcol` https://github.com/JuliaData/DataFrames.jl/issues/2636
- [ ] extend row-like outputs handling in combine et al https://github.com/JuliaData/DataFrames.jl/issues/2576
- [ ] type of array returned in transformations https://github.com/JuliaData/DataFrames.jl/issues/2569 and https://github.com/JuliaData/DataFrames.jl/issues/2567
- [ ] grouping `PooledArrays` improvements https://github.com/JuliaData/DataFrames.jl/issues/2564
- [ ] PrettyTables.jl related houskeeping https://github.com/JuliaData/DataFrames.jl/issues/2525
- [ ] type instability in aggregation https://github.com/JuliaData/DataFrames.jl/issues/2424
- [ ] improve using of aggregation fast path https://github.com/JuliaData/DataFrames.jl/issues/2423

**Comment by bkamins** [comment]
I am closing this as now the labeling of 1.0 milestone is precise enough to track it there. Essentially we only need some minor clean-ups before 1.0 release.
